display_errors = On
display_startup_errors = On
error_reporting = E_ALL
allow_url_fopen = On
allow_url_include = On
session.cookie_httponly = 0
session.cookie_samesite =
upload_max_filesize = 20M
post_max_size = 25M
max_execution_time = 120
default_charset = "UTF-8"
date.timezone = Asia/Shanghai
